export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_PRODUCT_LIST_PAGE = 'SET_PRODUCT_LIST_PAGE';
export const ADD_ITEMS_TO_PRODUCT_LIST = 'ADD_ITEMS_TO_PRODUCT_LIST';
export const SET_PRODUCT_LIST_IS_LOAD_MORE = 'SET_PRODUCT_LIST_IS_LOAD_MORE';
export const SET_PRODUCT_ALL_COUNT = 'SET_PRODUCT_ALL_COUNT';
export const SET_PRODUCT_IS_LOADING = 'SET_PRODUCT_IS_LOADING';

export const SET_CART = 'SET_CART';
export const ADD_CART_LIST_ITEM = 'ADD_CART_LIST_ITEM';
export const SET_CART_IS_SHOW = 'SET_CART_IS_SHOW';

export const SET_PRODUCT_ITEM = 'SET_PRODUCT_ITEM';
export const RESET_PRODUCT_ITEM_PROPS = 'RESET_PRODUCT_ITEM_PROPS';
export const CHANGE_PRODUCT_ITEM_COLOR = 'CHANGE_PRODUCT_ITEM_COLOR';
export const CHANGE_PRODUCT_ITEM_SIZE = 'CHANGE_PRODUCT_ITEM_SIZE';
export const INCREASE_PRODUCT_ITEM_COUNTER = 'INCREASE_PRODUCT_ITEM_COUNTER';
export const DECREASE_PRODUCT_ITEM_COUNTER = 'DECREASE_PRODUCT_ITEM_COUNTER';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_SEARCH_IS_OPEN = 'SET_SEARCH_IS_OPEN';
export const SET_SEARCH_IS_ACTIVE = 'SET_SEARCH_IS_ACTIVE';

export const SET_FILTER_COLOR = 'SET_FILTER_COLOR';
export const SET_FILTER_IS_ACTIVE = 'SET_FILTER_IS_ACTIVE';
export const SET_FILTER_SORT_PRICE = 'SET_FILTER_SORT_PRICE';
export const SET_FILTER_COLLECTION = 'SET_FILTER_COLLECTION';
export const CLEAN_FILTER = 'CLEAN_FILTER';
export const SET_FILTER_IS_OPEN = 'SET_FILTER_IS_OPEN';

export const SET_CATEGORY = 'SET_CATEGORY';